apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: users-webapi
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  # type: LoadBalancer
